# Generated by Django 6.0 on 2026-01-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="number_snils",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Введите номер СНИЛС",
                null=True,
                verbose_name="номер СНИЛС",
            ),
        ),
    ]
