# Generated by Django 6.0 on 2026-01-09 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=200, verbose_name="Имя сотрудника"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="Фамилия сотрудника"),
                ),
                (
                    "photo_employee",
                    models.ImageField(
                        upload_to="photos/", verbose_name="Фото сотрудника"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=200, verbose_name="Должность"),
                ),
                (
                    "specialization",
                    models.TextField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Специализация",
                    ),
                ),
                (
                    "work_experience",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Стаж работы"
                    ),
                ),
            ],
            options={
                "verbose_name": "сотрудник",
                "verbose_name_plural": "сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        verbose_name="Название организации медицинской диагностики",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/",
                        verbose_name="Логотип организации медицинской диагностики",
                    ),
                ),
                (
                    "story",
                    models.TextField(
                        blank=True, null=True, verbose_name="История организации"
                    ),
                ),
                (
                    "mission",
                    models.TextField(blank=True, null=True, verbose_name="Миссия"),
                ),
                (
                    "values",
                    models.TextField(blank=True, null=True, verbose_name="Ценности"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание организации"
                    ),
                ),
            ],
            options={
                "verbose_name": "организация",
                "verbose_name_plural": "организации",
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Лабораторные исследования", "Лабораторные исследования"),
                            ("Терапевт", "Терапевт"),
                            ("УЗИ", "УЗИ"),
                            (
                                "Функциональная диагностика",
                                "Функциональная диагностика",
                            ),
                        ],
                        default="Терапевт",
                        help_text="Укажите услугу",
                        max_length=200,
                        verbose_name="Оказываемая услуга",
                    ),
                ),
                (
                    "cabinet_number",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Номер кабинета"
                    ),
                ),
                (
                    "description_service",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание услуги"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor",
                        to="organisation.employee",
                        verbose_name="Специалист",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
